function set_console_state(self, enabled)
	self.active = enabled
	msg.post("console", self.active and "enable" or "disable")
	if self.active then msg.post(".", "acquire_input_focus") end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	set_console_state(self, false)
end

function on_input(self, action_id, action)
	if action_id == hash("console_toggle") and action.pressed then
		set_console_state(self, not self.active)
	end
end